site_name: quotonic-public
repo_url: https://github.com/jewaniuk/quotonic-public
site_url: https://jewaniuk.github.io/quotonic-public
site_description: A platform for performing efficient simulations in the quantum photonic domain.
site_author: Jacob Ewaniuk
edit_uri: edit/main/docs/
repo_name: jewaniuk/quotonic-public
copyright: Maintained by <a href="https://jewaniuk.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jewaniuk/quotonic-public
    - icon: fontawesome/brands/python
      link: https://pypi.com/project/quotonic-public

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true